import React,{useEffect,useMemo,useState} from 'react';
type Category='Mejeri'|'Grønt & frugt'|'Protein'|'Kolonial'|'Brød & morgenmad'|'Øvrigt';
type Ingredient={id:string;name:string;emoji:string;category:Category};
type Recipe={id:number;title:string;time:number;tag:string;emoji:string;ingredients:string[];steps:string[]};
type ShoppingItem={id:string;name:string;emoji:string;category:Category;done:boolean};
const ingredients:Ingredient[]=[
{id:'mælk',name:'Mælk',emoji:'🥛',category:'Mejeri'},{id:'fløde',name:'Fløde',emoji:'🥛',category:'Mejeri'},{id:'mozzarella',name:'Mozzarella',emoji:'🧀',category:'Mejeri'},{id:'revet ost',name:'Revet ost',emoji:'🧀',category:'Mejeri'},{id:'creme fraiche',name:'Creme fraiche',emoji:'🥣',category:'Mejeri'},
{id:'tomat',name:'Tomat',emoji:'🍅',category:'Grønt & frugt'},{id:'broccoli',name:'Broccoli',emoji:'🥦',category:'Grønt & frugt'},{id:'gulerod',name:'Gulerod',emoji:'🥕',category:'Grønt & frugt'},{id:'peberfrugt',name:'Peberfrugt',emoji:'🫑',category:'Grønt & frugt'},{id:'løg',name:'Løg',emoji:'🧅',category:'Grønt & frugt'},{id:'hvidløg',name:'Hvidløg',emoji:'🧄',category:'Grønt & frugt'},{id:'kartofler',name:'Kartofler',emoji:'🥔',category:'Grønt & frugt'},{id:'spinat',name:'Spinat',emoji:'🥬',category:'Grønt & frugt'},{id:'majs',name:'Majs',emoji:'🌽',category:'Grønt & frugt'},{id:'bananer',name:'Bananer',emoji:'🍌',category:'Grønt & frugt'},
{id:'kylling',name:'Kylling',emoji:'🍗',category:'Protein'},{id:'hakket oksekød',name:'Hakket oksekød',emoji:'🥩',category:'Protein'},{id:'laks',name:'Laks',emoji:'🐟',category:'Protein'},{id:'æg',name:'Æg',emoji:'🥚',category:'Protein'},{id:'kikærter',name:'Kikærter',emoji:'🫘',category:'Protein'},{id:'halloumi',name:'Halloumi',emoji:'🧀',category:'Protein'},
{id:'pasta',name:'Pasta',emoji:'🍝',category:'Kolonial'},{id:'ris',name:'Ris',emoji:'🍚',category:'Kolonial'},{id:'hakket tomat',name:'Hakket tomat',emoji:'🥫',category:'Kolonial'},{id:'pesto',name:'Pesto',emoji:'🌿',category:'Kolonial'},{id:'tortillas',name:'Tortillas',emoji:'🌯',category:'Kolonial'},{id:'kokosmælk',name:'Kokosmælk',emoji:'🥥',category:'Kolonial'},{id:'rød karry',name:'Rød karry',emoji:'🌶️',category:'Kolonial'},{id:'bouillon',name:'Bouillon',emoji:'🧂',category:'Kolonial'},
{id:'rugbrød',name:'Rugbrød',emoji:'🍞',category:'Brød & morgenmad'},{id:'havregryn',name:'Havregryn',emoji:'🥣',category:'Brød & morgenmad'},{id:'citron',name:'Citron',emoji:'🍋',category:'Øvrigt'},{id:'olivenolie',name:'Olivenolie',emoji:'🫒',category:'Øvrigt'},{id:'sojasauce',name:'Sojasauce',emoji:'🥢',category:'Øvrigt'}];
const recipes:Recipe[]=[
{id:1,title:'Cremet kyllingepasta',time:25,tag:'Familiefavorit',emoji:'🍝',ingredients:['kylling','pasta','fløde','løg','revet ost'],steps:['Kog pastaen efter pakken.','Steg kylling og løg på en pande.','Tilsæt fløde og revet ost, og lad saucen samle sig.','Vend pastaen i saucen og servér.']},
{id:2,title:'Laks med kartofler',time:30,tag:'Nem',emoji:'🐟',ingredients:['laks','kartofler','broccoli','citron'],steps:['Kog kartoflerne møre.','Bag laksen i ovnen med citron.','Damp broccoli kort.','Servér det hele sammen.']},
{id:3,title:'Tacos med kylling',time:20,tag:'Børnene elsker',emoji:'🌮',ingredients:['kylling','tortillas','majs','tomat','revet ost'],steps:['Steg kylling i små stykker.','Varm tortillas.','Skær tomat og gør majs klar.','Lad alle samle deres egne tacos.']},
{id:4,title:'Spaghetti bolognese',time:35,tag:'Klassiker',emoji:'🍝',ingredients:['hakket oksekød','pasta','hakket tomat','løg','gulerod'],steps:['Steg kød, løg og revet gulerod.','Tilsæt hakket tomat.','Lad saucen simre.','Kog pasta og servér.']},
{id:5,title:'Pesto-pasta med mozzarella',time:15,tag:'Supernem',emoji:'🌿',ingredients:['pasta','pesto','mozzarella','tomat','spinat'],steps:['Kog pastaen.','Vend med pesto.','Tilsæt tomat, spinat og mozzarella.','Servér med lidt olivenolie.']},
{id:6,title:'Kylling i rød karry',time:25,tag:'Lidt anderledes',emoji:'🍛',ingredients:['kylling','ris','kokosmælk','rød karry','peberfrugt'],steps:['Kog risene.','Steg kylling og peberfrugt.','Tilsæt karry og kokosmælk.','Lad retten simre og servér med ris.']},
{id:7,title:'Halloumi-bowl',time:20,tag:'Grøn favorit',emoji:'🥗',ingredients:['halloumi','ris','broccoli','majs','tomat'],steps:['Kog ris.','Steg halloumi gylden.','Damp broccoli.','Saml bowl med grønt og majs.']},
{id:8,title:'Tomatpasta med spinat',time:20,tag:'Billig & nem',emoji:'🍅',ingredients:['pasta','hakket tomat','spinat','løg','hvidløg'],steps:['Kog pasta.','Steg løg og hvidløg.','Tilsæt tomat og spinat.','Vend pastaen i saucen.']},
{id:9,title:'Tortilla-pizza',time:15,tag:'Børnevenlig',emoji:'🍕',ingredients:['tortillas','hakket tomat','mozzarella','peberfrugt','majs'],steps:['Læg tortillas på en bageplade.','Smør med tomat.','Fordel ost og grønt.','Bag til osten er gylden.']},
{id:10,title:'Æggekage med grønt',time:20,tag:'Hurtig',emoji:'🍳',ingredients:['æg','mælk','kartofler','spinat','tomat'],steps:['Pisk æg og mælk.','Steg kartofler og grønt.','Hæld æggemassen over.','Lad den sætte sig og servér.']},
{id:11,title:'Kikærte-curry',time:25,tag:'Uden kød',emoji:'🥥',ingredients:['kikærter','ris','kokosmælk','rød karry','spinat'],steps:['Kog ris.','Varm karry og kokosmælk.','Tilsæt kikærter og spinat.','Lad det simre og servér med ris.']},
{id:12,title:'Laks med pesto og kartofler',time:25,tag:'Nem hverdagsmad',emoji:'🐟',ingredients:['laks','kartofler','pesto','broccoli','citron'],steps:['Kog kartofler.','Bag laks med pesto og citron.','Damp broccoli.','Servér sammen.']}];
const byId=Object.fromEntries(ingredients.map(i=>[i.id,i]));
const categories:Category[]=['Mejeri','Grønt & frugt','Protein','Kolonial','Brød & morgenmad','Øvrigt'];
const days=['Mandag','Tirsdag','Onsdag','Torsdag','Fredag','Lørdag','Søndag'];
const defaultPlan:Record<string,string|null>={Mandag:'Cremet kyllingepasta',Tirsdag:'Rugbrød + rester',Onsdag:'Laks med kartofler',Torsdag:'Tacos med kylling',Fredag:'Pizza',Lørdag:'Burger',Søndag:'Familiefavorit'};
const starterItems:ShoppingItem[]=[{id:'s1',name:'Kylling',emoji:'🍗',category:'Protein',done:false},{id:'s2',name:'Pasta',emoji:'🍝',category:'Kolonial',done:false},{id:'s3',name:'Fløde',emoji:'🥛',category:'Mejeri',done:false},{id:'s4',name:'Broccoli',emoji:'🥦',category:'Grønt & frugt',done:false},{id:'s5',name:'Mælk',emoji:'🥛',category:'Mejeri',done:false},{id:'s6',name:'Bananer',emoji:'🍌',category:'Grønt & frugt',done:false}];
const loadStored=<T,>(key:string,fallback:T):T=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}};
function Button({children,onClick,kind='primary'}:{children:React.ReactNode;onClick?:()=>void;kind?:'primary'|'secondary'|'soft'}){return <button className={`ka-btn ${kind}`} onClick={onClick}>{children}</button>}
function Alf(){return <div className="alf-mark">👩‍🍳</div>}
export default function AppNext(){
const [page,setPage]=useState('home'),[plan,setPlan]=useState<Record<string,string|null>>(()=>loadStored('ka-plan',defaultPlan)),[shopping,setShopping]=useState<ShoppingItem[]>(()=>loadStored('ka-shopping',starterItems)),[recipe,setRecipe]=useState<Recipe|null>(null),[targetDay,setTargetDay]=useState<string|null>(null),[selectedCategory,setSelectedCategory]=useState<Category|null>(null),[selectedIngredient,setSelectedIngredient]=useState<string|null>(null),[manual,setManual]=useState(''),[search,setSearch]=useState('');
useEffect(()=>{localStorage.setItem('ka-plan',JSON.stringify(plan))},[plan]);useEffect(()=>{localStorage.setItem('ka-shopping',JSON.stringify(shopping))},[shopping]);
const filteredRecipes=useMemo(()=>recipes.filter(r=>(!selectedIngredient||r.ingredients.includes(selectedIngredient))&&(!search||r.title.toLowerCase().includes(search.toLowerCase())||r.ingredients.some(id=>byId[id].name.toLowerCase().includes(search.toLowerCase())))),[selectedIngredient,search]);
const openRecipe=(r:Recipe,day?:string)=>{setTargetDay(day??null);setRecipe(r)};
const chooseForDay=(day:string)=>{setTargetDay(day);setPage('recipes')};
const addRecipe=(r:Recipe,day:string)=>{setPlan(p=>{const next={...p};Object.keys(next).forEach(d=>{if(d!==day&&next[d]===r.title)next[d]=null});next[day]=r.title;return next});setShopping(items=>{const names=new Set(items.map(i=>i.name.toLowerCase()));const extra=r.ingredients.filter(id=>!names.has(byId[id].name.toLowerCase())).map(id=>({id:`r-${r.id}-${id}-${Date.now()}`,name:byId[id].name,emoji:byId[id].emoji,category:byId[id].category,done:false}));return [...items,...extra]});setRecipe(null);setTargetDay(null);setPage('plan')};
const clearDay=(day:string)=>setPlan(p=>({...p,[day]:null}));
const syncShopping=()=>setShopping(items=>{const names=new Set(items.map(i=>i.name.toLowerCase()));const wanted=Object.values(plan).flatMap(title=>{const r=recipes.find(x=>x.title===title);return r?r.ingredients:[]});const extra=[...new Set(wanted)].filter(id=>!names.has(byId[id].name.toLowerCase())).map(id=>({id:`plan-${id}-${Date.now()}`,name:byId[id].name,emoji:byId[id].emoji,category:byId[id].category,done:false}));return [...items,...extra]});
const toggleItem=(id:string)=>setShopping(items=>items.map(i=>i.id===id?{...i,done:!i.done}:i));const addManual=()=>{const v=manual.trim();if(!v)return;setShopping(s=>[...s,{id:`m-${Date.now()}`,name:v,emoji:'🛒',category:'Øvrigt',done:false}]);setManual('')};const clearDone=()=>setShopping(s=>s.filter(i=>!i.done));
return <div className="ka-app"><header className="ka-header"><button className="ka-brand" onClick={()=>setPage('home')}><Alf/><span><b>KøkkenAlf</b><small>Din lille hjælper i køkkenet</small></span></button><nav>{[['home','Hjem'],['plan','📅 Madplan'],['recipes','🍲 Opskrifter'],['shopping','🛒 Indkøb']].map(([k,l])=><button key={k} className={page===k?'active':''} onClick={()=>setPage(k)}>{l}</button>)}</nav></header><main>{page==='home'&&<Home go={setPage} open={openRecipe}/>} {page==='recipes'&&<Recipes rs={filteredRecipes} category={selectedCategory} setCategory={setSelectedCategory} ingredient={selectedIngredient} setIngredient={setSelectedIngredient} open={(r)=>openRecipe(r,targetDay??undefined)} search={search} setSearch={setSearch}/>} {page==='plan'&&<MealPlan plan={plan} chooseDay={chooseForDay} openRecipe={(r,d)=>openRecipe(r,d)} clearDay={clearDay} syncShopping={syncShopping} recipes={recipes}/>} {page==='shopping'&&<Shopping shopping={shopping} toggle={toggleItem} manual={manual} setManual={setManual} addManual={addManual} clearDone={clearDone} syncShopping={syncShopping}/>}</main><footer>♡ KøkkenAlf · mindre stress, mere madglæde</footer>{recipe&&<RecipeModal recipe={recipe} initialDay={targetDay} close={()=>{setRecipe(null);setTargetDay(null)}} add={addRecipe}/>}</div>}
function Home({go,open}:{go:(p:string)=>void;open:(r:Recipe)=>void}){return <section className="ka-home"><div className="ka-hero"><div><span className="ka-eyebrow">🍴 Hverdagsmad uden hovedpine</span><h1>Hvad skal vi finde på i køkkenet?</h1><p>KøkkenAlf hjælper med opskrifter, madplan og indkøb – samlet ét sted.</p><div className="ka-actions"><Button onClick={()=>go('plan')}>📅 Se madplan</Button><Button kind="secondary" onClick={()=>go('recipes')}>🍲 Find opskrift</Button></div></div><div className="ka-hero-card"><div className="ka-alf-big">👩‍🍳</div><b>Find mad ud fra det, du har hjemme ✨</b><p>Vælg råvarer efter kategori og find retter, der passer til køleskabet.</p><Button kind="soft" onClick={()=>go('recipes')}>Se ingredienser →</Button></div></div><div className="ka-section-title"><span><i>⭐</i> Ugens favoritter</span><button onClick={()=>go('recipes')}>Se alle →</button></div><div className="ka-grid">{recipes.slice(0,4).map(r=><button className="ka-recipe-card" key={r.id} onClick={()=>open(r)}><div className="ka-recipe-img">{r.emoji}</div><small>{r.tag}</small><h3>{r.title}</h3><span>⏱ {r.time} min</span></button>)}</div></section>}
function Recipes({rs,category,setCategory,ingredient,setIngredient,open,search,setSearch}:{rs:Recipe[];category:Category|null;setCategory:(c:Category|null)=>void;ingredient:string|null;setIngredient:(s:string|null)=>void;open:(r:Recipe)=>void;search:string;setSearch:(s:string)=>void}){const cis=ingredients.filter(i=>!category||i.category===category);return <section className="ka-page"><span className="ka-eyebrow">🍲 Madglæde</span><h1>Opskrifter</h1><p className="ka-lead">Find inspiration efter råvare – eller søg på det, du har hjemme.</p><input className="ka-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="🔎 Søg efter ret eller ingrediens..."/><div className="ka-categories">{categories.map(c=><button className={category===c?'chosen':''} key={c} onClick={()=>{setCategory(category===c?null:c);setIngredient(null)}}>{c}</button>)}</div>{category&&<div className="ka-ingredients"><div className="ka-subhead"><b>{category}</b><button onClick={()=>setIngredient(null)}>Alle</button></div><div className="ka-ing-grid">{cis.map(i=><button className={ingredient===i.id?'chosen':''} key={i.id} onClick={()=>setIngredient(ingredient===i.id?null:i.id)}><span>{i.emoji}</span>{i.name}</button>)}</div></div>}<div className="ka-results-head"><b>{ingredient?`Opskrifter med ${byId[ingredient].name}`:'Alle opskrifter'}</b><span>{rs.length} forslag</span></div><div className="ka-grid">{rs.map(r=><button className="ka-recipe-card" key={r.id} onClick={()=>open(r)}><div className="ka-recipe-img">{r.emoji}</div><small>{r.tag}</small><h3>{r.title}</h3><span>⏱ {r.time} min</span></button>)}</div>{!rs.length&&<div className="ka-empty">Ingen opskrifter fundet endnu – prøv en anden råvare. 💛</div>}</section>}
function MealPlan({plan,chooseDay,openRecipe,clearDay,syncShopping,recipes:rs}:{plan:Record<string,string|null>;chooseDay:(d:string)=>void;openRecipe:(r:Recipe,d:string)=>void;clearDay:(d:string)=>void;syncShopping:()=>void;recipes:Recipe[]}){return <section className="ka-page"><span className="ka-eyebrow">📅 Ugens overblik</span><h1>Madplan</h1><p className="ka-lead">Planlæg ugen – og skift nemt mening, hvis tirsdag pludselig bliver onsdag. 😄</p><div className="ka-plan-actions"><Button onClick={syncShopping}>🛒 Opdater indkøb fra madplan</Button><Button kind="secondary" onClick={()=>chooseDay(days[0])}>🍲 Vælg opskrift</Button></div><div className="ka-plan">{days.map(day=>{const title=plan[day],r=rs.find(x=>x.title===title);return <div className="ka-day" key={day}><div><b>{day}</b><span>{r?`⏱ ${r.time} min`:''}</span></div>{r?<button onClick={()=>openRecipe(r,day)}><span>{r.emoji}</span><strong>{r.title}</strong><small>Skift ret →</small></button>:<button onClick={()=>chooseDay(day)}>+ Vælg aftensmad</button>}{r&&<button className="ka-day-clear" onClick={()=>clearDay(day)}>Fjern fra dagen</button>}</div>})}</div><div className="ka-note">💡 Tryk på en planlagt ret for at skifte den. Den nye ret erstatter den gamle på den valgte dag.</div></section>}
function Shopping({shopping,toggle,manual,setManual,addManual,clearDone,syncShopping}:{shopping:ShoppingItem[];toggle:(id:string)=>void;manual:string;setManual:(s:string)=>void;addManual:()=>void;clearDone:()=>void;syncShopping:()=>void}){const done=shopping.filter(i=>i.done).length;return <section className="ka-page"><span className="ka-eyebrow">🛒 På tur i butikken</span><h1>Indkøbsliste</h1><p className="ka-lead">Ingredienser fra din madplan kommer automatisk her. Tryk på en vare, når den er i kurven.</p><div className="ka-shopping-top"><span>{done} af {shopping.length} købt</span><div>{done>0&&<button onClick={clearDone}>Fjern købte</button>}<button onClick={syncShopping}>🔄 Opdater fra madplan</button></div></div><div className="ka-add"><input value={manual} onChange={e=>setManual(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addManual()} placeholder="Tilføj selv en vare..."/><button onClick={addManual}>+ Tilføj</button></div><div className="ka-shop-categories">{categories.map(c=>{const items=shopping.filter(i=>i.category===c);if(!items.length)return null;return <section className="ka-shop-group" key={c}><h2><span>{categoryEmoji(c)}</span>{c}<small>{items.length}</small></h2><div>{items.map(i=><button className={`ka-shop-item ${i.done?'done':''}`} key={i.id} onClick={()=>toggle(i.id)}><span className="ka-check">{i.done?'✓':'○'}</span><span className="ka-shop-emoji">{i.emoji}</span><strong>{i.name}</strong></button>)}</div></section>})}</div>{!shopping.length&&<div className="ka-empty">Indkøbslisten er tom 🎉</div>}</section>}
function categoryEmoji(c:Category){return ({'Mejeri':'🥛','Grønt & frugt':'🥦','Protein':'🍗','Kolonial':'🍝','Brød & morgenmad':'🍞','Øvrigt':'🧂'})[c]}
function RecipeModal({recipe,initialDay,close,add}:{recipe:Recipe;initialDay:string|null;close:()=>void;add:(r:Recipe,d:string)=>void}){const [day,setDay]=useState(initialDay||days[0]);return <div className="ka-modal-backdrop" onClick={close}><div className="ka-modal" onClick={e=>e.stopPropagation()}><button className="ka-close" onClick={close}>×</button><div className="ka-modal-emoji">{recipe.emoji}</div><span className="ka-eyebrow">{recipe.tag} · ⏱ {recipe.time} min</span><h2>{recipe.title}</h2><h3>Ingredienser</h3><div className="ka-modal-ingredients">{recipe.ingredients.map(id=><span key={id}>{byId[id].emoji} {byId[id].name}</span>)}</div><h3>Sådan gør du</h3><ol>{recipe.steps.map(s=><li key={s}>{s}</li>)}</ol><div className="ka-add-plan"><label>{initialDay?'Skift retten på':'Læg retten i'} madplan:</label><select value={day} onChange={e=>setDay(e.target.value)}>{days.map(d=><option key={d}>{d}</option>)}</select><Button onClick={()=>add(recipe,day)}>📅 {initialDay?'Gem ændring':'Tilføj til madplan'}</Button></div></div></div>}
